config/routes.rb
Rails.application.routes.draw do

  get '/users' => 'users#index'

  get 'github/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'github#index'

end

app/models/language.rb
class Language < ActiveRecord::Base
  belongs_to :user

  validates :language, presence: true
end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :user

  module Association
    def find_or_create auth
      provider = where(provider:auth.provider, uid:auth.uid).first
      provider ||= create!(provider:auth.provider, uid:auth.uid)
    end
  end
end

app/models/user.rb
require "open-uri"

class User < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :omniauthable, :confirmable, :recoverable, :registerable, :rememberable

  has_many :providers, :extend => Provider::Association
  has_many :points
  has_many :languages

  validates :screen_name, :uniqueness => true, :allow_blank => true
  validates :email, :uniqueness => true, :allow_blank => true
  validates :github, :uniqueness => true, :allow_blank => true

  def as_json(options)
    super(options.merge(methods: [:current_languages]))
  end

  def self.provider(auth, provider_id)

    auth_uid = auth.uid
    find_hash = { auth_uid: auth_uid } if auth_uid.present?
    find_hash = { email: auth.info.email } if auth.info.email

    github = ""
    if provider_id == :github
      github = auth.info.nickname
      find_hash = { github: github }
    end

    first_name = auth.info.first_name.presence || auth.info.name.split.first || ""
    last_name = auth.info.last_name.presence || auth.info.name.split.last || ""

    raise "Not enough information provided" unless find_hash.present?

    user = where(find_hash).first
    transaction do
      if user
        user.update_attribute :first_name, first_name if first_name.present?
        user.update_attribute :last_name, last_name if last_name.present?
        user.update_attribute :auth_uid, auth_uid unless user.auth_uid.present?
        user.update_attribute :confirmed_at, DateTime.now unless user.confirmed_at.present?
      else
        create_hash = { auth_uid: auth_uid, github: github, first_name: first_name, last_name: last_name, password: Devise.friendly_token[0,20], :confirmed_at => DateTime.now }
        create_hash[:email] = auth.info.email.presence
        user = User.create!(create_hash)
      end

      github_info = auth.extra.raw_info.slice(*%w(avatar_url blog location hireable public_repos public_gists followers following))

      user.avatar_url = github_info["avatar_url"]
      user.blog = github_info["blog"]
      user.location = github_info["location"]
      user.hireable = github_info["hireable"]
      user.public_repos = github_info["public_repos"]
      user.public_gists = github_info["public_gists"]
      user.followers = github_info["followers"]
      user.following = github_info["following"]

      user.save!

      user.providers.find_or_create(auth)
    end
  end

  def current_languages
    languages.map(&:language)
  end

  def update_github
    repos = ActiveSupport::JSON.decode open("https://api.github.com/users/#{github}/repos").read
    all_gh_languages = repos.map { |e| e["language"] }.uniq.compact
    new_languages = all_gh_languages - current_languages
    new_languages.each do |nl|
      self.languages << Language.create(language: nl)
    end
  end

  protected
  def confirmation_required?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/github_controller.rb
class GithubController < ApplicationController
  layout false

  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    provider :facebook
  end

  def github
    provider :github
  end

  def twitter
    provider :twitter
  end

  def google_apps
    provider :google_apps
  end

  private
  def after_sign_in_path_for(resource)
    session[:redirect] || root_path
  end

  def provider provider_id
    @user = User.provider(request.env["omniauth.auth"], provider_id).user
    session["devise.#{provider_id}_data"] = request.env["omniauth.auth"]
    flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => (provider_id == :google_apps ? :gmail : provider_id).to_s.titleize

    if session[:entries].present?
      Entry.where(:id => session[:entries]).update_all ["user_id = ?", @user.id]
      session[:entries] = nil
    end

    sign_in_and_redirect @user.reload, :event => :authentication
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    online = current_user ? User.all : []
    render json: online
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/github/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>    <html class="lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>    <html class="lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class=""> <!--<![endif]-->
<head>
  <title>GetHub</title>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
  <div class="nm-navbar navbar navbar-default" role="navigation">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li><a href="/">GetHub</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li><p class="navbar-text"><%= current_user.github %></p></li>
            <li><%= link_to "LOGOUT", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to content_tag(:i, "", :class=> "fa fa-github-square gray") + " Login", omniauth_authorize_path('user', :github) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="container">
    <div id="flash">
      <% if alert %> <div id="alert" class="alert alert-warning text-center"> <%= alert %> </div> <% end %>
      <% if notice %> <div id="notice" class="alert alert-success text-center"> <%= notice %> </div> <% end %>
    </div>

    <div id="react">
      <i class="fa fa-spin fa-spinner fa-2x"></i>
    </div>
  </div>

  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <script src="/react/react.js"></script>
  <script src="/react/JSXTransformer.js"></script>
  <script type="text/jsx" src="/react/main.js"></script>
</body>
</html>